### PR TITLE
Compile Windows jd11 with VS2019

### PR DESCRIPTION
**Pull request by pshipton**
Closes https://github.com/eclipse-openj9/openj9/issues/15582
See also https://github.com/adoptium/temurin-build/pull/2992

### CODE REVIEW

**Comment by pshipton** [comment]
@AdamBrousseau for your review as well as https://github.com/ibmruntimes/temurin-build/pull/25

**Comment by pshipton** [comment]
Do you want me to open a PR at Adoptium as well with this change and other previous changes for OpenJ9?

**Comment by pshipton** [comment]
Opened https://github.com/adoptium/temurin-build/pull/3085 for the previous changes.

**Comment by pshipton** [comment]
@AdamBrousseau are you thinking about merging this, or do you want me to make the change at Adoptium and get it from there?

**Comment by AdamBrousseau** [comment]
We'll want the change at Adopt too. I need to fix merge conflicts in the mirrors right now. If I don't get around to that soon we can merge this in the meantine.

**Review by AdamBrousseau — APPROVED** [review]

**Comment by pshipton** [comment]
Created https://github.com/adoptium/temurin-build/pull/3098

**Pull request merged**
